Etw service
Velocidex/velociraptor pull request #3069
Opened 2023-11-03 04:04 UTC by bmcder02

Changed watch_etw to support multiple providers under a single session. Should address issue #2944 .

2023-11-03 04:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Velocidex/velociraptor?pullRequest=3069) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Velocidex/velociraptor?pullRequest=3069) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Velocidex/velociraptor?pullRequest=3069) it.</sub>

2023-11-06 02:57 UTC, scudette requested changes

2023-11-06 02:57 UTC, scudette commented on vql/windows/etw/watcher.go
> +		sessionContext.mu.Lock()
Move this method to the context itself.

2023-11-06 02:57 UTC, scudette commented on vql/windows/etw/watcher.go
> +			if handle.guid != wGuid {
we probably need to manage keywords better here

2023-11-06 02:57 UTC, scudette commented on vql/windows/etw/watcher.go
> +			scope, scope, constants.EVTX_FREQUENCY)
we dont need this

2023-11-06 02:57 UTC, scudette commented on vql/windows/etw/watcher.go
> +	}
dont need this

2023-11-06 02:57 UTC, scudette commented on vql/windows/etw/watcher.go
> +		handles := sessionContext.registrations
Might be worth taking a copy here just in case

2023-11-06 02:57 UTC, scudette commented on vql/windows/etw/watcher.go
> +	delete(GlobalEventTraceService.sessions, self.name)
move to a method - this is not thread safe

2023-11-06 04:41 UTC, scudette requested changes

2023-11-06 04:41 UTC, scudette commented on vql/windows/etw/watcher.go
> +		// err = sessionContext.UpdateSession(ctx, scope, wGuid, any_keyword, all_keyword, level)
clean up?

2023-11-06 04:41 UTC, scudette commented on vql/windows/etw/watcher.go
> +	sessionContext.mu.Lock()
move to a method on session

2023-11-06 04:41 UTC, scudette commented on vql/windows/etw/watcher.go
> +		sessionContext.mu.Lock()
move to method

2023-11-07 06:27 UTC, bmcder02 commented
Waiting on ETW library change to be merged before Windows Test will pass.

2023-11-13 01:50 UTC, merged